### PR TITLE
Add R example and sample data

### PR DESCRIPTION
**Pull request by RaoOfPhysics**
Here you go, @betatim!

### CODE REVIEW

**Comment by betatim** [comment]
Thanks a bunch! You will be there to explain it right?

**Comment by RaoOfPhysics** [comment]
@betatim: What's there to explain? ;)

Seriously, though, yes, I will be there and I will try to explain what's going on. But if @tpmccauley is around, it'll be even better!

**Comment by betatim** [comment]
What the heck is a global muon? In particular if you are not a CERNiac

**Comment by RaoOfPhysics** [comment]
A round muon, of course. What else could it be? :P

Sure, I think even I could explain that.

**Comment by betatim** [comment]
I tried to keep my examples fairly generic with the aim that we could share
them with other study groups who don't have access to particle physicists
-> this is why there is no ROOT anywhere for example.

We can work out some comments or links that let others understand what some
of the terms are.

**Comment by RaoOfPhysics** [comment]
You are correct, I could've gone with something simpler. But:
- this example shows a cool usecase for our open data, and
- the code was already written, so making a Notebook from it also makes our own documentation better.

Was killing multiple birds. Or so I thought.

**Comment by tpmccauley** [comment]
for our purposes, a global muon is a high-quality muon reconstructed in both the inner detector (i.e. the tracker) and the outer detector (i.e. the muon chambers).

**Comment by betatim** [comment]
I like it and it will be interesting for none CERNiacs for sure! I just
wanted to mention that we need to up our communications effort ;)

**Comment by tpmccauley** [comment]
@RaoOfPhysics it may be better to add the full csv file (with all events, not just a subset of them given by _N). It makes for a nicer dimuon spectrum.

**Comment by RaoOfPhysics** [comment]
@tpmccauley: My apologies, what am I missing and what should I change?

**Comment by tpmccauley** [comment]
Nothing to apologize for :) 
Just perhaps a better plot in the end if you use MuRun2010B.csv instead of MuRun2010B_N.csv from 
http://opendata.cern.ch/record/700

**Comment by RaoOfPhysics** [comment]
@tpmccauley: Ah ha! Ok! :D

**Pull request merged**
